package jpuppeteer.cdp.client.entity.input;

/**
*/
public class DispatchKeyEventRequest {

    /**
    * Type of the key event.
    */
    public final String type;

    /**
    * Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
    */
    public final Integer modifiers;

    /**
    * Time at which the event occurred.
    */
    public final java.math.BigDecimal timestamp;

    /**
    * Text as generated by processing a virtual key code with a keyboard layout. Not needed for for `keyUp` and `rawKeyDown` events (default: "")
    */
    public final String text;

    /**
    * Text that would have been generated by the keyboard if no modifiers were pressed (except for shift). Useful for shortcut (accelerator) key handling (default: "").
    */
    public final String unmodifiedText;

    /**
    * Unique key identifier (e.g., 'U+0041') (default: "").
    */
    public final String keyIdentifier;

    /**
    * Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
    */
    public final String code;

    /**
    * Unique DOM defined string value describing the meaning of the key in the context of active modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
    */
    public final String key;

    /**
    * Windows virtual key code (default: 0).
    */
    public final Integer windowsVirtualKeyCode;

    /**
    * Native virtual key code (default: 0).
    */
    public final Integer nativeVirtualKeyCode;

    /**
    * Whether the event was generated from auto repeat (default: false).
    */
    public final Boolean autoRepeat;

    /**
    * Whether the event was generated from the keypad (default: false).
    */
    public final Boolean isKeypad;

    /**
    * Whether the event was a system key event (default: false).
    */
    public final Boolean isSystemKey;

    /**
    * Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default: 0).
    */
    public final Integer location;

    public DispatchKeyEventRequest(String type, Integer modifiers, java.math.BigDecimal timestamp, String text, String unmodifiedText, String keyIdentifier, String code, String key, Integer windowsVirtualKeyCode, Integer nativeVirtualKeyCode, Boolean autoRepeat, Boolean isKeypad, Boolean isSystemKey, Integer location) {
        this.type = type;
        this.modifiers = modifiers;
        this.timestamp = timestamp;
        this.text = text;
        this.unmodifiedText = unmodifiedText;
        this.keyIdentifier = keyIdentifier;
        this.code = code;
        this.key = key;
        this.windowsVirtualKeyCode = windowsVirtualKeyCode;
        this.nativeVirtualKeyCode = nativeVirtualKeyCode;
        this.autoRepeat = autoRepeat;
        this.isKeypad = isKeypad;
        this.isSystemKey = isSystemKey;
        this.location = location;
    }

    public DispatchKeyEventRequest(String type) {
        this.type = type;
        this.modifiers = null;
        this.timestamp = null;
        this.text = null;
        this.unmodifiedText = null;
        this.keyIdentifier = null;
        this.code = null;
        this.key = null;
        this.windowsVirtualKeyCode = null;
        this.nativeVirtualKeyCode = null;
        this.autoRepeat = null;
        this.isKeypad = null;
        this.isSystemKey = null;
        this.location = null;
    }

}