package jpuppeteer.chrome.event.type;

import jpuppeteer.cdp.cdp.CDPEventType;

import static jpuppeteer.cdp.cdp.CDPEventType.*;

public enum ChromeBrowserEvent {

    //target
    TARGETCREATED(CDPEventType.TARGET_TARGETCREATED),
    TARGETDESTROYED(CDPEventType.TARGET_TARGETDESTROYED),
    TARGETCRASHED(CDPEventType.TARGET_TARGETCRASHED),
    ATTACHEDTOTARGET(CDPEventType.TARGET_ATTACHEDTOTARGET),
    TARGETINFOCHANGED(CDPEventType.TARGET_TARGETINFOCHANGED),
    DETACHEDFROMTARGET(CDPEventType.TARGET_DETACHEDFROMTARGET),
    RECEIVEDMESSAGEFROMTARGET(CDPEventType.TARGET_RECEIVEDMESSAGEFROMTARGET),

    //page
    LIFECYCLEEVENT(CDPEventType.PAGE_LIFECYCLEEVENT),
    DOMCONTENTEVENTFIRED(CDPEventType.PAGE_DOMCONTENTEVENTFIRED),
    LOADEVENTFIRED(CDPEventType.PAGE_LOADEVENTFIRED),
    FRAMEATTACHED(CDPEventType.PAGE_FRAMEATTACHED),
    FRAMEDETACHED(CDPEventType.PAGE_FRAMEDETACHED),
    FRAMENAVIGATED(CDPEventType.PAGE_FRAMENAVIGATED),
    JAVASCRIPTDIALOGOPENING(CDPEventType.PAGE_JAVASCRIPTDIALOGOPENING),

    //network
    REQUESTWILLBESENT(CDPEventType.NETWORK_REQUESTWILLBESENT),
    RESPONSERECEIVED(CDPEventType.NETWORK_RESPONSERECEIVED),
    LOADINGFAILED(CDPEventType.NETWORK_LOADINGFAILED),
    LOADINGFINISHED(CDPEventType.NETWORK_LOADINGFINISHED),

    //runtime
    EXCEPTIONTHROWN(CDPEventType.RUNTIME_EXCEPTIONTHROWN),
    EXECUTIONCONTEXTCREATED(CDPEventType.RUNTIME_EXECUTIONCONTEXTCREATED),
    EXECUTIONCONTEXTDESTROYED(CDPEventType.RUNTIME_EXECUTIONCONTEXTDESTROYED),
    EXECUTIONCONTEXTSCLEARED(RUNTIME_EXECUTIONCONTEXTSCLEARED),

    //fetch
    REQUESTPAUSED(FETCH_REQUESTPAUSED),
    AUTHREQUIRED(FETCH_AUTHREQUIRED),

    //log
    ENTRYADDED(CDPEventType.LOG_ENTRYADDED),
    ;

    private CDPEventType eventType;

    ChromeBrowserEvent(CDPEventType eventType) {
        this.eventType = eventType;
    }

    public CDPEventType getEventType() {
        return eventType;
    }
}
